# -*- coding: utf-8 -*-

from odoo import models, fields, api
from odoo.exceptions import UserError, ValidationError


class AccountAnalyticDefault(models.Model):
	_inherit = 'account.analytic.default'

	company_id = fields.Many2one('res.company',string=u'Compa√±ia',required=True, default=lambda self: self.env.company,readonly=True)